apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "azure-gar-cred.fullname" . }}-refresh
  labels:
    {{- include "azure-gar-cred.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      {{- include "azure-gar-cred.job" . | nindent 6 }}
