apiVersion: v2
name: azure-gar-cred
description: GAR credentials job for AKS. Required when pulling Formal images from GAR and requires `pullWithCredentials=true` in the Connector and Satellite Helm chart values.
type: application
version: 0.1.0
