apiVersion: v2
name: azure-gar-cred
description: GAR credentials job for AKS. Required when pulling Formal images from GAR with `pullWithCredentials=true` in workload chart values.
type: application
version: 0.1.0
