apiVersion: v2
name: policy-data-loader-satellite
description: The Formal Policy Data Loader Satellite executes customer-defined code to load arbitrary external data into connector context.
type: application
version: 0.6.0
dependencies:
  - name: formal-common
    version: 0.1.0
    repository: file://../formal-common
