apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "connector.fullname" . }}-ecr-cred-refresh
  labels:
    {{- include "connector.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      {{- include "connector.ecrJob" . | nindent 6 }}
