apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connector.fullname" . }}-ecr
  labels:
    {{- include "connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"  # Run before the ECR job (-10)
type: Opaque
data:
  ecr-access-key-id: {{ .Values.ecrAccessKeyId | b64enc }}
  ecr-secret-access-key: {{ .Values.ecrSecretAccessKey | b64enc }}
