apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-operator.fullname" . }}
  labels:
    {{- include "kubernetes-operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    metricsAddr: ":{{ .Values.metricsPort }}"
    {{- with .Values.reconcileInterval }}
    reconcileInterval: {{ . | quote }}
    {{- end }}
