apiVersion: v1
kind: Service
metadata:
  name: {{ include "formal-common.fullname" . }}
  labels:
    {{- include "formal-common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 50056
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "formal-common.selectorLabels" . | nindent 6 }}
