{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "formal-common.serviceAccountName" . }}
  labels:
    {{- include "formal-common.labels" . | nindent 4 }}
{{- end }}
