{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "connector.serviceAccountName" . }}
  labels:
    {{- include "connector.labels" . | nindent 4 }}
{{- end }}
